basePath: /
host: https://ws-agung-2024-b77249100221.herokuapp.com
info:
  contact:
    email: 714220039@std.ulbi.ac.id
    name: API Support
    url: https://github.com/agung6544
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
